Dln/users
CognotektGmbH/terraform-provider-jumpcloud pull request #3
Opened 2018-12-21 15:33 UTC by daniellohausen

2019-01-08 15:54 UTC, gypsydiver requested changes
Added some comments, please see #4

2019-01-08 15:54 UTC, gypsydiver commented on jumpcloud/resource_user.go
> +func populateUserPayload(d *schema.ResourceData) *jcapiv1.Systemuserputpost {
This could be removed.

2019-01-08 15:54 UTC, gypsydiver commented on jumpcloud/resource_user.go
> +	configv1 := jcapiv1.NewConfiguration()
We could create a v2tov1 function to keep it dry.

2019-01-08 15:54 UTC, gypsydiver commented on jumpcloud/resource_user.go
> +	var payload jcapiv1.Systemuserputpost
Personally, I'm not a fan of this notation how about:
```go 
payload := jcapiv1.Systemuserputpost{
		Username:                    d.Get("username").(string),
		Email:                       d.Get("email").(string),
		Firstname:                   d.Get("firstname").(string),
		Lastname:                    d.Get("lastname").(string),
		EnableUserPortalMultifactor: d.Get("enable_mfa").(bool),
}
```

2019-01-08 15:54 UTC, gypsydiver commented on jumpcloud/resource_user.go
> +	// The code fomr the create function is almost identical, but the structure is different :
typo

2019-01-09 08:24 UTC, daniellohausen commented on jumpcloud/resource_user.go
> +	var payload jcapiv1.Systemuserputpost
Done

2019-01-09 11:02 UTC, gypsydiver commented
:sake:

2019-01-09 11:02 UTC, gypsydiver approved these changes

2019-01-09 11:03 UTC, merged